pipeline:
  slack:
    image: plugins/slack
    secrets: [ slack_webhook ]
    channel: deployments
    username: drone
    template: "<{{build.link}}|Deployment #{{build.number}} started> on <http://github.com/{{repo.owner}}/{{repo.name}}/tree/{{build.branch}}|{{repo.name}}:{{build.branch}}> by {{build.author}}"
    when:
      branch: [ master ]
  docker:
    image: plugins/docker
    repo: jakobferdinandsen/gudni
    dockerfile: Dockerfile
    secrets: [ docker_username, docker_password ]
    tags:
      - latest
      - ${DRONE_COMMIT}
  rancher:
    image: peloton/drone-rancher
    url: https://ranch.jhaaf.dk
    secrets: [ rancher_access_key, rancher_secret_key ]
    service: gudni/gudni
    docker_image: jakobferdinandsen/gudni:latest
    confirm: true
    timeout: 240
    batch_size: 2
  slack:
    image: plugins/slack
    secrets: [ slack_webhook ]
    channel: deployments
    username: drone
    when:
      branch: [ master ]
      status: [ success, failure ]