pipeline:
  slack:
    image: plugins/slack
    webhook: https://discordapp.com/api/webhooks/435477252751491082/z-nWvNh_an54RHExnSWicGKackzUhjOUOTPMKPX1np--yRG2ghdatjoDRCzoVsyGKuXj/slack
    channel: deployments
    username: drone
    template: "<{{build.link}}|Deployment #{{build.number}} started> on <http://github.com/{{repo.owner}}/{{repo.name}}/tree/{{build.branch}}|{{repo.name}}:{{build.branch}}> by {{build.author}}"
    when:
      branch: [ master ]
  docker:
    image: plugins/docker
    repo: jakobferdinandsen/gudni
    dockerfile: Dockerfile
    secrets: [ docker_username, docker_password ]
    tags:
      - latest
  rancher:
    image: peloton/drone-rancher
    url: https://ranch.jhaaf.dk
    access_key: ${RANCHER_ACCESS_KEY}
    secret_key: ${RANCHER_SECRET_KEY}
    service: gudni
    docker_image: jakobferdinandsen/gudni:latest
    confirm: true
    timeout: 240
  slack:
    image: plugins/slack
    webhook: https://discordapp.com/api/webhooks/435477252751491082/z-nWvNh_an54RHExnSWicGKackzUhjOUOTPMKPX1np--yRG2ghdatjoDRCzoVsyGKuXj/slack
    channel: deployments
    username: drone
    when:
      branch: [ master ]
      status: [ success, failure ]